---
# file: tasks/repo.tml
- name: Install Percona repository packages
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb
- name: Update apt cache
  apt: update_cache=yes

